"""
Package Manager (spec section 14). Assembles the final reproducible
project folder + metadata.json + README, matching the exact layout
specified in the design doc.
"""
from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict

from schemas.simulation_plan import SimulationPlan


def build_package(simulation_name: str, output_root: Path, plan: SimulationPlan,
                   structure_files: Dict[str, Path], pw_in_path: Path,
                   upf_paths: Dict[str, str], slurm_path: Path) -> Path:
    root = output_root / simulation_name
    (root / "00_structure").mkdir(parents=True, exist_ok=True)
    (root / "01_quantum_espresso").mkdir(parents=True, exist_ok=True)
    (root / "02_pseudopotentials").mkdir(parents=True, exist_ok=True)
    (root / "03_slurm").mkdir(parents=True, exist_ok=True)

    for fmt, path in structure_files.items():
        shutil.copy(path, root / "00_structure" / path.name)

    shutil.copy(pw_in_path, root / "01_quantum_espresso" / "pw.in")

    for element, upf in upf_paths.items():
        shutil.copy(upf, root / "02_pseudopotentials" / Path(upf).name)

    shutil.copy(slurm_path, root / "03_slurm" / "job.slurm")

    metadata = {
        "original_user_request": plan.request.raw_user_text,
        "parsed_request": json.loads(plan.request.model_dump_json()),
        "resolved_parameters": {
            k: json.loads(v.model_dump_json()) for k, v in plan.resolved_parameters.items()
        },
        "pseudopotentials": {el: Path(p).name for el, p in upf_paths.items()},
        "warnings": plan.warnings,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    (root / "metadata.json").write_text(json.dumps(metadata, indent=2))

    readme = f"""# {simulation_name}

Generated by AMSA on {metadata['generated_at_utc']}.

## Original request
> {plan.request.raw_user_text}

## Contents
- `00_structure/` — CIF/XYZ/VASP structure files for visual inspection
- `01_quantum_espresso/pw.in` — deterministic QE input file
- `02_pseudopotentials/` — UPF files used for this calculation
- `03_slurm/job.slurm` — HPC job script (NOT submitted automatically)
- `metadata.json` — full provenance of every parameter

## Before you submit
1. Open the structure in a visualizer (VESTA / OVITO / ASE GUI) and confirm
   geometry, doping site, and adsorbate placement look correct.
2. Review `metadata.json` -> resolved_parameters for anything marked
   "rule_recommendation" instead of "user" -- these are AMSA defaults,
   not your explicit choices.
3. Check `job.slurm` partition/module names match your actual cluster.
4. Only then run: sbatch job.slurm

## Warnings raised during generation
{chr(10).join('- ' + w for w in plan.warnings) if plan.warnings else '(none)'}
"""
    (root / "README.md").write_text(readme)

    return root
